version: "3.8"
services:
  mokepon:
    image: node:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/mokepon
      - /mokepon/node_modules
    environment:
      NODE_ENV: production